---
- name: Playbook para configurar MySQL
  hosts: aws
  become: yes

  vars:
    db:
      name: db_name
      user: db_user
      password: db_password

  tasks:

    - name: Instalamos el módulo de pymysql
      apt:
        name: python3-pymysql
        state: present

    - name: Crear una base de datos
      mysql_db:
        name: "{{ db.name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock 

    # El parámetro 'no_log: true' lo utilizamos para ocultar información de salida
    - name: Crear el usuario de la base de datos
      no_log: true
      mysql_user:         
        name: "{{ db.user }}"
        password: "{{ db.password }}"
        priv: "{{ db.name }}.*:ALL"
        #host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock 