---
- name: Playbook para instalar herramientas adicionales
  hosts: aws
  become: yes

  vars:
    - phpmyadmin_user: pma_user
    - phpmyadmin_password: pma_password
    - phpmyadmin_db_name: db_name

  tasks:

    - name: Descargar phpMyAdmin
      get_url:
        url: https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.zip
        dest: /tmp/phpMyAdmin-5.2.0-all-languages.zip

    - name: Instalar unzip
      apt:
        name: unzip
        state: present

    - name: Descomprimir phpMyAdmin
      unarchive:
        src: /tmp/phpMyAdmin-5.2.0-all-languages.zip
        dest: /tmp/
        remote_src: yes

    - name: Copiar phpMyAdmin
      copy:
        src: /tmp/phpMyAdmin-5.2.0-all-languages/
        dest: /var/www/html/phpmyadmin
        remote_src: yes

    - name: Cambiar el propietario y el grupo de phpMyAdmin
      file:
        path: /var/www/html/phpmyadmin
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Instalar pip3
      apt:
        name: python3-pip
        state: present

    - name: Instalar PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Crear la base de datos para phpMyAdmin
      mysql_db:
        name: "{{ phpmyadmin_db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Importar la base de datos de phpMyAdmin
      mysql_db:
        name: "{{ phpmyadmin_db_name }}"
        state: import
        target: /var/www/html/phpmyadmin/sql/create_tables.sql
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear el usuario de phpMyAdmin
      mysql_user:
        name: "{{ phpmyadmin_user }}"
        password: "{{ phpmyadmin_password }}"
        priv: "{{ phpmyadmin_db_name }}.*:ALL"
        #host: '%'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock