---
- name: Playbook para instalar la pila LAMP
  hosts: aws
  become: yes

  tasks:

    - name: Actualizar los repositorios
      command: apt update

    - name: Instalar el servidor web Apache
      command: apt install apache2 -y

    - name: Instalar el sistema gestor de bases de datos MySQL
      command: apt install mysql-server -y

    - name: Instalar PHP
      command: apt install php libapache2-mod-php php-mysql -y

    - name: Reiniciar el servicio de Apache
      command: systemctl restart apache2